import React from "react";
import { createFileRoute } from "@tanstack/react-router";

import { getSystemInfo } from "../ipc/renderer.js";
import { SystemInfo } from "../../components/SystemInfo.js";

export const Route = createFileRoute("/about")({
  component: RouteComponent,
  loader: () => getSystemInfo(),
});

function RouteComponent() {
  const { platform, arch }: ISystemInfo = Route.useLoaderData();

  return (
    <div className="p-4">
      <h1 className="my-2 text-2xl">About</h1>
      <p className="text-sm">This route is generated by TanStack Router.</p>
      <SystemInfo platform={platform} arch={arch} />
    </div>
  );
}
